# Generated by Django 2.2.8 on 2019-12-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.CharField(blank=True, max_length=255, null=True, verbose_name='List CSS Classes (eg. text-primary py-0 fa-2x)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (eg Latest School Bulletin)')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link to resource (eg tel:+62-061-661-6765)')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='FA Icon (eg. fas fa-newspaper fa-fw)')),
            ],
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='calendarurl',
            field=models.URLField(blank=True, null=True, verbose_name='URL for calendar'),
        ),
        migrations.AddField(
            model_name='googlemaps',
            name='mapurl',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Map URL'),
        ),
    ]
