# Generated by Django 2.2.8 on 2019-12-09 11:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('tools', '0002_auto_20191206_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='auto_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.AddField(
            model_name='social',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description (eg. Latest School Bulletin)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='css',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List CSS Classes (eg. text-primary py-0)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FA Icon (eg. fas fa-newspaper fa-fw fa-2x)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (eg. December Bulletin)'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tools.Item')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
