# Generated by Django 2.2.4 on 2019-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20191209_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='intro',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='body',
        ),
    ]
