# Generated by Django 2.2.8 on 2019-12-12 20:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20191212_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlemaps',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlemaps',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock(label='external URL', required=False))]))], blank=True, null=True),
        ),
    ]
