# Generated by Django 2.2.8 on 2019-12-15 15:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20191212_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlemaps',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlemaps',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='end',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))]))], blank=True, null=True),
        ),
    ]
