# Generated by Django 2.2.8 on 2020-02-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('tools', '0007_auto_20200218_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlemaps',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='googlemaps',
            name='seo_image',
        ),
        migrations.DeleteModel(
            name='GoogleCalendar',
        ),
        migrations.DeleteModel(
            name='GoogleMaps',
        ),
    ]
